import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import benjerry from "../data/bj_product.json";

export default function BJ() {
  return (
    <>
      <Head>
        <title>Ben & Jerry's Icecream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button>
            <Link href="/haagen_dazs">
              Haagen Dazs Icecream
            </Link>
        </button>
        <div>
          {benjerry.map((bj, index) => {
            return (
              <div key={index}>
                <Image
                  src={bj.picture}
                  alt={bj.name}
                  width={200}
                  height={200}
                />
                <h3>{bj.name}</h3>
                <p>{bj.subhead}</p>
                <p>{bj.rating}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
