import Head from "next/head";
import Image from "next/image";
import haagen from "../data/hd_product.json";

export default function HD() {
  return (
    <>
      <Head>
        <title>Haagen Dazs Icecream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {
            haagen.map((hd, index) => {
              return (
                <div key={index}>

                  <Image
                    src={hd.picture}
                    alt={hd.name}
                    width={200}
                    height={200}
                  />
                  <h3>{hd.name}</h3>
                  <p>{hd.description}</p>
                  <p>{hd.rating}</p>
                </div>
              )
            })
          }
        </div>
      </main>
    </>
  )
}
