import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import benjerry from '../data/bj_product.json'
import haagen from '../data/hd_product.json'


export default function Home() {
  return (
    <>
      <Head>
        <title>Find Icecream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {
            benjerry.map((bj, index) => {
              return (
                <div key={index}>

                  <Image
                    src={bj.picture}
                    alt={bj.name}
                    width={200}
                    height={200}
                  />
                  <h3>{bj.name}</h3>
                  <p>{bj.subhead}</p>
                  <p>{bj.rating}</p>
                </div>
              )
            })
          }
        </div>
      </main>
    </>
  )
}
