import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import benjerry from '../data/bj_product.json'
import haagen from '../data/hd_product.json'


export default function Home() {
  return (
    <>
      <Head>
        <title>Find Icecream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <h1>Find a variety of Icecream flavours!</h1>
        
        <div>
          <button>
            <Link href="/benNjerry">
              Ben & Jerry's Icecream
            </Link>
          </button>
          <button>
            <Link href="/haagen_dazs">
              Haagen Dazs Icecream
            </Link>
          </button>
        </div>
      </main>
    </>
  )
}
